public with sharing class test_ctrl_GoogleMaps_Accounts {

    public String travelTime { get; set; }

    public String duration { get; set; }

    public String distance { get; set; }

    public PageReference btnCalculateDistance_Click() {
        return null;
    }


    public String account2Id { get; set; }

    public String accountOptions { get; set; }

    public String account1Id { get; set; }
}